// SPDX-License-Identifier: Apache-2.0

package fakegen

import (
	"bytes"
	"fmt"
	"go/format"
	"text/template"
)

// Emit renders the programmable in-memory fake for a service contract as Go
// source. The output is a single self-contained file declaring:
//
//   - A Fake type embedding the generated Unimplemented<Service>Server, so it
//     satisfies the server interface and stays forward-compatible if the
//     contract grows an RPC before this fake is regenerated (the embedded
//     Unimplemented arm returns codes.Unimplemented — a loud, contract-honest
//     default, never a silent zero value).
//   - Per-method programmable responders (canned responses) and a recorder
//     (recorded calls) — the doc 06 §2.1 "behavior-specified stand-in, not a
//     null stub" contract.
//   - A Register helper mirroring the generated RegisterXxxServiceServer.
//
// The file is gofmt-canonical and deterministic, so it commits under
// proto/gen/go and re-emits to a byte-identical result (codegen-drift
// discipline, proto/FREEZE.md).
func Emit(model *ServiceModel) ([]byte, error) {
	var buf bytes.Buffer
	if err := fakeTemplate.Execute(&buf, model); err != nil {
		return nil, fmt.Errorf("fakegen: execute template for %s: %w", model.ServiceName, err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("fakegen: gofmt emitted fake for %s: %w\n--- raw ---\n%s",
			model.ServiceName, err, buf.String())
	}
	return formatted, nil
}

var fakeTemplate = template.Must(template.New("fake").Funcs(template.FuncMap{
	"qual":   func(m *ServiceModel, t string) string { return m.StubPackageName + "." + t },
	"stream": func(k StreamKind) string { return k.String() },
}).Parse(fakeTemplateSrc))

// fakeTemplateSrc is the fake-server source template. It is intentionally
// readable rather than minimal: a fake a downstream team builds against is read
// far more than it is written, and the recorded-call / canned-response surface
// is the part teams program directly.
const fakeTemplateSrc = `// Code generated by assurance/contract-harness/fakegen. DO NOT EDIT.
//
// Programmable in-memory fake for {{.ServiceName}} (doc 06 §2.1, doc 15 §5.6).
// This is a behavior-specified stand-in — canned responses plus recorded calls
// — NOT a null stub. Downstream workstreams build against this fake; the
// dual-run harness (assurance/contract-harness/dualrun) runs the seam's single
// conformance suite against BOTH this fake and the real implementation and fails
// on divergence (D24/D14).

package {{.FakePackageName}}

import (
	"context"
{{- if .NeedsIO}}
	"io"
{{- end}}
	"sync"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	{{.StubPackageName}} "{{.StubImportPath}}"
)
{{$model := .}}{{$svc := .GoServiceName}}
{{range .Methods}}
// {{$svc}}{{.Name}}Call is one recorded call to {{$svc}}.{{.Name}}.
type {{$svc}}{{.Name}}Call struct {
{{- if or (eq (stream .Kind) "client-stream") (eq (stream .Kind) "bidi-stream")}}
	// Reqs holds every message the client streamed.
	Reqs []*{{qual $model .InputGoType}}
{{- else}}
	Req *{{qual $model .InputGoType}}
{{- end}}
}
{{end}}
// {{$svc}}Fake is the programmable in-memory fake for {{.ServiceName}}. The zero
// value is usable: every method returns codes.Unimplemented until a responder is
// set, which is the contract-honest default (a fake that silently returns zero
// values is exactly the "lying fake" the dual-run harness exists to catch). Set
// the per-method responder fields to program canned behavior; read the
// recorded-call slices (via the accessor methods) to assert what was called. All
// exported fields and methods are safe for concurrent use. The type is named per
// service so multiple services sharing one generated package do not collide.
type {{$svc}}Fake struct {
	{{.StubPackageName}}.Unimplemented{{.GoServiceName}}Server

	mu sync.Mutex
{{range .Methods}}
	// {{.Name}}Responder, if set, services {{.Name}}. If nil, {{.Name}} returns
	// codes.Unimplemented.
{{- if eq (stream .Kind) "unary"}}
	{{.Name}}Responder func(ctx context.Context, req *{{qual $model .InputGoType}}) (*{{qual $model .OutputGoType}}, error)
{{- else if eq (stream .Kind) "client-stream"}}
	// reqs is the full set of streamed messages; the responder returns the single
	// response sent when the client half-closes.
	{{.Name}}Responder func(ctx context.Context, reqs []*{{qual $model .InputGoType}}) (*{{qual $model .OutputGoType}}, error)
{{- else if eq (stream .Kind) "server-stream"}}
	// The responder returns the ordered responses streamed back to the client.
	{{.Name}}Responder func(ctx context.Context, req *{{qual $model .InputGoType}}) ([]*{{qual $model .OutputGoType}}, error)
{{- else}}
	// Bidi: the responder maps the streamed requests to the ordered responses.
	{{.Name}}Responder func(ctx context.Context, reqs []*{{qual $model .InputGoType}}) ([]*{{qual $model .OutputGoType}}, error)
{{- end}}
	{{.Name}}Calls []{{$svc}}{{.Name}}Call
{{end}}
}

// New{{$svc}}Fake returns a ready-to-program {{$svc}}Fake.
func New{{$svc}}Fake() *{{$svc}}Fake { return &{{$svc}}Fake{} }
{{range .Methods}}
{{if eq (stream .Kind) "unary"}}
func (f *{{$svc}}Fake) {{.Name}}(ctx context.Context, req *{{qual $model .InputGoType}}) (*{{qual $model .OutputGoType}}, error) {
	f.mu.Lock()
	f.{{.Name}}Calls = append(f.{{.Name}}Calls, {{$svc}}{{.Name}}Call{Req: req})
	responder := f.{{.Name}}Responder
	f.mu.Unlock()
	if responder == nil {
		return nil, status.Errorf(codes.Unimplemented, "fake {{$model.ServiceName}}: {{.Name}} responder not programmed")
	}
	return responder(ctx, req)
}
{{else if eq (stream .Kind) "client-stream"}}
func (f *{{$svc}}Fake) {{.Name}}(stream grpc.ClientStreamingServer[{{qual $model .InputGoType}}, {{qual $model .OutputGoType}}]) error {
	var reqs []*{{qual $model .InputGoType}}
	for {
		req, err := stream.Recv()
		if err == io.EOF {
			break
		}
		if err != nil {
			return err
		}
		reqs = append(reqs, req)
	}
	f.mu.Lock()
	f.{{.Name}}Calls = append(f.{{.Name}}Calls, {{$svc}}{{.Name}}Call{Reqs: reqs})
	responder := f.{{.Name}}Responder
	f.mu.Unlock()
	if responder == nil {
		return status.Errorf(codes.Unimplemented, "fake {{$model.ServiceName}}: {{.Name}} responder not programmed")
	}
	resp, err := responder(stream.Context(), reqs)
	if err != nil {
		return err
	}
	return stream.SendAndClose(resp)
}
{{else if eq (stream .Kind) "server-stream"}}
func (f *{{$svc}}Fake) {{.Name}}(req *{{qual $model .InputGoType}}, stream grpc.ServerStreamingServer[{{qual $model .OutputGoType}}]) error {
	f.mu.Lock()
	f.{{.Name}}Calls = append(f.{{.Name}}Calls, {{$svc}}{{.Name}}Call{Req: req})
	responder := f.{{.Name}}Responder
	f.mu.Unlock()
	if responder == nil {
		return status.Errorf(codes.Unimplemented, "fake {{$model.ServiceName}}: {{.Name}} responder not programmed")
	}
	resps, err := responder(stream.Context(), req)
	if err != nil {
		return err
	}
	for _, r := range resps {
		if err := stream.Send(r); err != nil {
			return err
		}
	}
	return nil
}
{{else}}
func (f *{{$svc}}Fake) {{.Name}}(stream grpc.BidiStreamingServer[{{qual $model .InputGoType}}, {{qual $model .OutputGoType}}]) error {
	var reqs []*{{qual $model .InputGoType}}
	for {
		req, err := stream.Recv()
		if err == io.EOF {
			break
		}
		if err != nil {
			return err
		}
		reqs = append(reqs, req)
	}
	f.mu.Lock()
	f.{{.Name}}Calls = append(f.{{.Name}}Calls, {{$svc}}{{.Name}}Call{Reqs: reqs})
	responder := f.{{.Name}}Responder
	f.mu.Unlock()
	if responder == nil {
		return status.Errorf(codes.Unimplemented, "fake {{$model.ServiceName}}: {{.Name}} responder not programmed")
	}
	resps, err := responder(stream.Context(), reqs)
	if err != nil {
		return err
	}
	for _, r := range resps {
		if err := stream.Send(r); err != nil {
			return err
		}
	}
	return nil
}
{{end}}
// {{.Name}}Recorded returns a copy of the calls recorded against {{$svc}}.{{.Name}}.
func (f *{{$svc}}Fake) {{.Name}}Recorded() []{{$svc}}{{.Name}}Call {
	f.mu.Lock()
	defer f.mu.Unlock()
	out := make([]{{$svc}}{{.Name}}Call, len(f.{{.Name}}Calls))
	copy(out, f.{{.Name}}Calls)
	return out
}
{{end}}
// Register{{$svc}} registers this fake on a grpc.ServiceRegistrar, mirroring the
// generated {{.StubPackageName}}.Register{{.GoServiceName}}Server so the fake
// drops into the dual-run harness exactly where the real server would.
func Register{{$svc}}(s grpc.ServiceRegistrar, f *{{$svc}}Fake) {
	{{.StubPackageName}}.Register{{.GoServiceName}}Server(s, f)
}
`
