#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# gen-attach-rules.sh — deterministic generator for the per-session attachment
# ruleset text the D66 attachment-primitive spike freezes (doc 09 §2/§8 Stage 1,
# OQ1/D66; sessions/round2/01). Output is the structural-audit forward-chain
# anchored on the `dstap-<idx>` contract (doc 14 §4) — NEVER on source IP.
#
# WHY THIS IS A GENERATOR, NOT HAND-WRITTEN STATE
#   The committed deliverable of a spike is the reproducible procedure, not a
#   blob (HARD FENCE). This script emits the same per-session forward anchors the
#   real session-create path will write through `ds-nft`, derived purely from the
#   frozen contract: tap name `dstap-<idx>`, per-session /31, guest IP `.1`. The
#   golden file `golden/attach-rules-n3.nft` pins the output so doc and grammar
#   cannot drift (same anti-drift pattern as the repo's `scripts/check-*.sh`
#   drift guards).
#
# SANDBOX-VERIFIED vs HOST-ONLY (stated, per the spike's honest-split obligation)
#   The `iifname` + `ip saddr` + counter/drop/accept subset emitted here was
#   APPLIED inside `unshare -rn` on the dev sandbox (rule application proven —
#   see run-attach-spike.sh phase B). The `ct state` half is HOST-ONLY: the
#   sandbox netns has no conntrack hooks, so `nft -f` and even `nft -c` reject
#   any `ct state` expression there. To keep the apply-half exercisable in the
#   sandbox, the conntrack `established,related` accept line is emitted only when
#   --with-ct is passed; the golden (and the real host ruleset) carry it.
#
# Usage:
#   gen-attach-rules.sh [N] [--with-ct]
#     N         number of sessions to emit anchors for (default 3)
#     --with-ct include the `ct state established,related accept` line (host shape)
set -euo pipefail

n=3
with_ct=0
for arg in "$@"; do
  case "$arg" in
    --with-ct) with_ct=1 ;;
    ''|*[!0-9]*) ;;            # ignore non-numeric flags
    *) n="$arg" ;;
  esac
done

printf '# generated by gen-attach-rules.sh — DO NOT HAND-EDIT (D66 attach spike, doc 14 §4)\n'
printf '# per-session forward isolation anchors: iifname "dstap-<idx>" + own /31 guest IP\n'
printf '# sessions: %s   with-ct: %s\n' "$n" "$with_ct"
printf 'table inet ds_attach_audit {\n'
printf '\tchain forward {\n'
printf '\t\ttype filter hook forward priority filter; policy drop;\n'
if [ "$with_ct" -eq 1 ]; then
  printf '\t\tct state established,related accept\n'
fi
i=0
while [ "$i" -lt "$n" ]; do
  # Per-session /31 (RFC 3021): 10.77.<idx>.0/31 — host gateway .0, guest .1.
  # The accept matches BOTH the unforgeable attachment point (iifname) AND the
  # session's own assigned guest IP (ip saddr), so a guest spoofing another
  # session's source address still falls through to the counted drop. This is
  # the D44/D69 "three keys must agree" precondition expressed in the ruleset
  # (the ct-mark third key lands with NFT-5, not in this spike).
  printf '\t\tiifname "dstap-%s" ip saddr 10.77.%s.1 accept comment "s%s: only its own guest IP egresses"\n' "$i" "$i" "$i"
  i=$((i + 1))
done
printf '\t\tiifname "dstap-*" counter drop comment "any other tap-origin frame: dropped + counted"\n'
printf '\t}\n'
printf '}\n'
